[build]
  base = "frontend/vite-project"  # Set the base directory if your frontend is in a subfolder
  command ="npm install && npm run build"
  publish = "dist"  #  Corrected path

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
